"""Tests for the ProductType CRUD endpoints + built-in protection.

The 5 original packaging presets are seeded on first DB init (each test
gets a fresh DB via the isolated_paths fixture, so seeding runs in setup).
Custom rows can be created, edited, deleted; built-ins refuse mutation.
"""

from __future__ import annotations

from typing import Any

from fastapi.testclient import TestClient

# ----------------------------------------------------------------- LIST


def test_list_presets_includes_five_builtins(client: TestClient) -> None:
    """Fresh DB → seeded with the 5 documented built-ins."""
    res = client.get("/api/packaging/presets")
    assert res.status_code == 200
    body = res.json()
    keys = {p["id"] for p in body}
    expected = {
        "lotion_bottle_label",
        "cream_jar_label",
        "cream_box_tuck_end",
        "serum_dropper_label",
        "shampoo_pouch",
    }
    assert expected <= keys, f"missing built-ins: {expected - keys}"
    # All five carry the is_builtin flag.
    builtins = [p for p in body if p["id"] in expected]
    assert all(p["is_builtin"] is True for p in builtins)


def test_product_types_endpoint_returns_same_rows_as_presets(
    client: TestClient,
) -> None:
    """``/product-types`` is the canonical name; ``/presets`` is the alias.

    Both must return identical content so the frontend can migrate
    gradually."""
    a = client.get("/api/packaging/presets").json()
    b = client.get("/api/packaging/product-types").json()
    assert a == b


# ----------------------------------------------------------------- CREATE


def _new_custom(**overrides: Any) -> dict[str, Any]:
    """Default body for a valid custom product type create."""
    base = {
        "key": "custom_test_pouch",
        "label": "Custom Test Pouch",
        "description": "A workspace for the test suite to play with.",
        "trim_w_mm": 80.0,
        "trim_h_mm": 120.0,
        "bleed_mm": 3.0,
        "dpi": 300,
        "color_space": "CMYK",
        "generation_size": "1024x1536",
        "notes": "Generated by tests.",
    }
    base.update(overrides)
    return base


def test_create_custom_product_type_returns_row(client: TestClient) -> None:
    res = client.post("/api/packaging/product-types", json=_new_custom())
    assert res.status_code == 201, res.text
    body = res.json()
    assert body["id"] == "custom_test_pouch"
    assert body["is_builtin"] is False
    assert body["trim_mm"] == {"w": 80.0, "h": 120.0}
    assert body["bleed_mm"] == 3.0
    assert body["dpi"] == 300


def test_create_custom_then_use_in_workspace(client: TestClient) -> None:
    """End-to-end: create a custom type, then create a workspace under it.

    The workspace's frozen ``specs`` should reflect the custom values.
    """
    create_res = client.post(
        "/api/packaging/product-types",
        json=_new_custom(
            key="big_format_poster",
            label="Big format poster",
            trim_w_mm=297.0,
            trim_h_mm=420.0,  # A3
            bleed_mm=5.0,
        ),
    )
    assert create_res.status_code == 201, create_res.text

    ws_res = client.post(
        "/api/packaging/workspaces",
        json={"name": "Test poster job", "product_type": "big_format_poster"},
    )
    assert ws_res.status_code == 201, ws_res.text
    specs = ws_res.json()["specs"]
    assert specs["trim_mm"] == {"w": 297.0, "h": 420.0}
    assert specs["bleed_mm"] == 5.0
    assert specs["preset_id"] == "big_format_poster"


def test_create_collision_with_builtin_returns_409(client: TestClient) -> None:
    """Custom key can't shadow a built-in."""
    res = client.post(
        "/api/packaging/product-types",
        json=_new_custom(key="lotion_bottle_label"),
    )
    assert res.status_code == 409
    assert "lotion_bottle_label" in res.json()["detail"]


def test_create_collision_with_existing_custom_returns_409(
    client: TestClient,
) -> None:
    client.post("/api/packaging/product-types", json=_new_custom()).raise_for_status()
    res = client.post("/api/packaging/product-types", json=_new_custom())
    assert res.status_code == 409


def test_create_validates_required_dimensions(client: TestClient) -> None:
    """trim_w_mm and trim_h_mm must be > 0."""
    res = client.post(
        "/api/packaging/product-types",
        json=_new_custom(trim_w_mm=0),
    )
    assert res.status_code == 422

    res2 = client.post(
        "/api/packaging/product-types",
        json=_new_custom(trim_h_mm=-5.0),
    )
    assert res2.status_code == 422


def test_create_validates_key_pattern(client: TestClient) -> None:
    """Key must be lowercase + digits + underscores. No spaces, no caps."""
    for bad_key in ("UPPER", "with-hyphen", "with space", "with.dot", ""):
        res = client.post(
            "/api/packaging/product-types",
            json=_new_custom(key=bad_key),
        )
        assert res.status_code == 422, f"key={bad_key!r} should be rejected"


# ----------------------------------------------------------------- UPDATE


def test_update_custom_changes_subset_of_fields(client: TestClient) -> None:
    """PATCH with partial body only modifies the supplied fields."""
    create = client.post(
        "/api/packaging/product-types", json=_new_custom()
    )
    create.raise_for_status()

    res = client.patch(
        "/api/packaging/product-types/custom_test_pouch",
        json={"label": "Renamed Pouch", "bleed_mm": 4.5},
    )
    assert res.status_code == 200, res.text
    body = res.json()
    assert body["label"] == "Renamed Pouch"
    assert body["bleed_mm"] == 4.5
    # Untouched fields preserved:
    assert body["trim_mm"] == {"w": 80.0, "h": 120.0}


def test_update_builtin_returns_409(client: TestClient) -> None:
    """Editing a built-in is refused; user is told to clone-and-rename."""
    res = client.patch(
        "/api/packaging/product-types/lotion_bottle_label",
        json={"label": "Hacked"},
    )
    assert res.status_code == 409
    detail = res.json()["detail"]
    assert "Built-in" in detail or "built-in" in detail
    assert "lotion_bottle_label" in detail


def test_update_unknown_key_returns_404(client: TestClient) -> None:
    res = client.patch(
        "/api/packaging/product-types/does_not_exist",
        json={"label": "Whatever"},
    )
    assert res.status_code == 404


def test_update_does_not_mutate_existing_workspaces(
    client: TestClient,
) -> None:
    """Spec is frozen at workspace creation — later product-type edits
    must NOT change the workspace's stored ``specs``."""
    # 1. Create a custom type + a workspace under it
    client.post("/api/packaging/product-types", json=_new_custom()).raise_for_status()
    ws_res = client.post(
        "/api/packaging/workspaces",
        json={"name": "Frozen", "product_type": "custom_test_pouch"},
    )
    ws_res.raise_for_status()
    slug = ws_res.json()["slug"]
    original_specs = ws_res.json()["specs"]

    # 2. Edit the product type (within validation bounds)
    client.patch(
        "/api/packaging/product-types/custom_test_pouch",
        json={"trim_w_mm": 999.0, "bleed_mm": 5.0},
    ).raise_for_status()

    # 3. The workspace's specs are unchanged
    refetch = client.get(f"/api/packaging/workspaces/{slug}").json()
    assert refetch["specs"] == original_specs


# ----------------------------------------------------------------- DELETE


def test_delete_custom_succeeds(client: TestClient) -> None:
    client.post("/api/packaging/product-types", json=_new_custom()).raise_for_status()
    res = client.delete("/api/packaging/product-types/custom_test_pouch")
    assert res.status_code == 204
    # Re-listing no longer includes it
    keys = {p["id"] for p in client.get("/api/packaging/presets").json()}
    assert "custom_test_pouch" not in keys


def test_delete_builtin_returns_409(client: TestClient) -> None:
    res = client.delete("/api/packaging/product-types/cream_jar_label")
    assert res.status_code == 409
    assert "Built-in" in res.json()["detail"] or "built-in" in res.json()["detail"]


def test_delete_in_use_by_workspace_returns_409(client: TestClient) -> None:
    """Custom row referenced by a workspace can't be removed."""
    client.post("/api/packaging/product-types", json=_new_custom()).raise_for_status()
    client.post(
        "/api/packaging/workspaces",
        json={"name": "Holder", "product_type": "custom_test_pouch"},
    ).raise_for_status()

    res = client.delete("/api/packaging/product-types/custom_test_pouch")
    assert res.status_code == 409
    detail = res.json()["detail"]
    assert "in use" in detail
    assert "1" in detail or "workspace" in detail


def test_delete_unknown_key_returns_404(client: TestClient) -> None:
    res = client.delete("/api/packaging/product-types/never_existed")
    assert res.status_code == 404
